name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ai_only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (AI project)
        working-directory: projects/03-ai-recs-validator
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run AI metrics + tests
        working-directory: projects/03-ai-recs-validator
        env:
          PYTHONPATH: .
        run: |
          mkdir -p reports
          python -m src.recommender --input data/tracks_features.csv --profiles data/user_profiles.json --out reports/metrics.json
          pytest -q